# Run Python pytests
# https://docs.microsoft.com/azure/devops/pipelines/languages/python
trigger:
 - master
 
pool:
  vmImage: 'Ubuntu 16.04'
strategy:
  matrix:
    Python37:
      PYTHON_VERSION: '3.7'
    Python36:
      PYTHON_VERSION: '3.6'
  maxParallel: 3

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(PYTHON_VERSION)'
    architecture: 'x64'
- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.pipelines.txt
    pip install pytest pytest-azurepipelines
  displayName: 'Install dependencies'
- script: |
    python -m pytest .
  env:
    DJANGO_SETTINGS_MODULE: tweeter3.settings.development
  displayName: 'pytest'